### ISSUE TITLE
Create new end point batch-create-wallet

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-wallet-api#349]
batch-create-wallet{
    “sender_wallet” : “WalletName”,
    “link_to_csv”: “https://abc.de/fgehg.csv”,
    “token_transfer_amount_default” : 5
}
// CSV file should have the following format
wallet_name, token_transfer_amount_overwrite

The logic needs to also check that the wallet might exist already in which case it should return a notification and not just stop but rather prompt "wallet ###WALLETNAME### already exists." and have a counter that counts the created wallets and the ones that are not created. The prompt at the end should read
x amount lines read
x wallets created
x wallets already exist

**Comment by dadiorchen** [comment]
@sebastiangaertner I think this api is harmful to our api, we should leave most of the responsibility to the client side, actually, based on our API (wallet + cofig) the client can implement it all by themselves right? 
1. It complicates the API knowledge/responsibility to let wallet API knows the config API, and handle things like: download CVS, uploading images
2. It is not so reusable, most likely we just implement this big API just for that single client.

If for some reason we have to implement something like this, I will choose a small API service to wrap this and isolate the invasion for APIs, I suggest the client take more responsibility for this:
1. Download the CVS, and translate it to the API (transfer API with bundle size)
2. Do the transfer
3. Upload the image for the wallet to our config API

**Comment by sebastiangaertner** [comment]
I thought is the client has a login and password and bearer token this API call is secure enough?

**Comment by dadiorchen** [comment]
@sebastiangaertner yea, it is fine in terms of secure, I'm worried about the healthy of the API, if we satisfy every requirement of patterns as they wish, we will get a complicated, hard to maintain, and buggy system, also, hard to reuse for all clients/partners. For example here, it is easy for the client to download by themselves and put it into the API requests like this:

```
{
  send_wallet: "xxx",
  batch_data: [
    {
        token_transfer_amount_overwrite: 5,
        wallet_name: "xxx",
        ...
    },{
        [second record],
    }
  ],
}
```

Let the API side request external resources is a bad decision, and brings risk and add unnecessary complexity to the server.

**Comment by dadiorchen** [comment]
I think:
1. This is an inefficient API endpoint to handle the case
2. Letting the server do extra work doesn't give too much relief for the client side, what if some records/wallets failed? The client sill need to handle the exception, in my opinion, letting the client handle the batch is easier for BOTH side, just like we do in the capture verification, we let the client side handle batch verification, and can stop at any point to check the problem.

**Comment by dadiorchen** [comment]
@sebastiangaertner what's the extra_wallet_data_about about?

**Comment by Kpoke** [comment]
One of the main issues @dadiorchen is the quantity, about 2000+, that is not really manageable using a json payload. A csv file is really the best way to go about that. And I also think it should be in the wallets api because the endpoints is closely related to the wallets domain. Also the endpoint would be reusable for any other user that wants to batch create wallets, unless we want to limit it to certain users @sebastiangaertner ?

**Comment by sebastiangaertner** [comment]
Yes, the endpoint will be used by other users eventually. 
@Kpoke we can leave the call to the extra_wallet out for now.

**Comment by dadiorchen** [comment]
@Kpoke Json has no limitation on POST requests, there is a limitation on the server side, but we can set it up to allow what we need. This is the simplest way to handle this, if we have to use CVS, we can still attach it as a file to the request body, in this case, we don't need to extra steps to download and face potential impact of outside service. 
Also, I don't feel a link for CVS is an easy way, If I was a client/partner I will hate the extra step to upload the file to a service and putting it into the API, it is cumbersome, right?
`Don't optimize the system too early`, I'd like to see we meet the size limitation the earlier the better, but a lot of result turns out to waste time coding.

**Comment by Kpoke** [comment]
@dadiorchen You're right about the csv, we can have them upload directly instead of a link.
