### ISSUE TITLE
Adjust API parameters for retrieving wallets 

### ISSUE THREAD

**Issue by mzyau** [Greenstand/treetracker-wallet-api#35]
Go through any relevant routes and reconfigure the logic so that the API accepts both wallet id [int] and wallet name [string] as a way to access the wallet.

**Comment by marcoboncoraglio** [comment]
Hey, quick question:
Would it suffice to change all the validation in the routes to accept either id or string for their wallet parameter, without changing logic in the wallet model? Since we have both getById and getByName implemented in our walletService, we would just call the appropriate method in our routes, depending on the input of the parameter. 

I noticed that the wallet routes are not yet implemented, and the only routes implemented that take wallets as inputs are in the auth and tranfer routers (transer and trust router after #39 gets pulled). Is it ok to patch these implemented routes for the scope of this issue, and everything we implement from this point on will follow the process described above?

**Comment by mzyau** [comment]
Yeah changing the parameters for /auth and /transfer could work, so we can leverage the the walletService functions as needed. Just make sure to update any structural changes to the api in the yaml file docs/api/spec so we're all on the same page.
